language: android

jdk:
 - oraclejdk7

before_install:
 - chmod +x gradlew

android:
  components:
    - build-tools-23.0.2
    - android-23

script: ./gradlew build

notifications:
  email: true

sudo: false